// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "0}3:r%[|R7cg:k;HN::1":
            case "raccoon boi":return img`
....d.....................d.........
....ddd.................ddd.........
....deddd.............ddded.........
....deeddd...........dddeed.........
....deeeddd.........dddeeed.........
....deeeedddddddddddddeeeed.........
....deeedddddddddddddddeeed.........
....deedddddddddddddddddeed.........
....deccccdddddddddddcccced.........
....dcccccccdddddddcccccccd.........
....eecccccccdddddcccccccee.........
....eeeeeeccccdddcccceeeeee.........
...eeeeeeeeecccdccceeeeeeeee........
...eeeeeeeeeeeccceeeeeeeeeee........
..eeeeeeeeeeeeeceeeeeeeeeeeee.......
..eeeeeeeeeeeeeeeeeeeeeeeeeee.......
.eeeeeeeeecceeeeeeecceeeeeeeee......
.eeeeeeeeecceeeeeeecceeeeeeeee......
eeeeeeeeeeeeedddddeeeeeeeeeeeee.....
eeeeeeeeeeedddddddddeeeeeeeeeee.....
..eeeeeeeeddddeeeddddeeeeeeee.......
....eeeeedddddeeedddddeeeee.........
......eedddddddddddddddee...........
.........ddddddddddddd..............
...........ddddddddd................
..............ede..........eeedddd..
..............eee.........eeeeeedddd
.............eeeee.......ddeeeeeedd.
............eeeeeee.....ddddeeeeeee.
...........eeeeeeeee....ddddddeeee..
...........ddeeeeedd....eddddddeee..
..........ddddeeedddd..eeeedddddde..
..........ddddddddddd..eeeeeeddddd..
..........dddddcddddd..eeeeeeedddd..
.........dddddcccddddd.ddeeeeeeddd..
.........dddddcccddddd.dddeeeeeee...
.........ddddcccccdddd.dddddeeeee...
.........ddddcccccdddd.ddddddeee....
.........ddddcccccddddeeedddddde....
.........ddddcccccddddeeeeddddd.....
.........ddddcccccddddeeeeedd.......
.........ddddcccccddddeeeee.........
.........dddcccccccdddddd...........
.........dddcccccccddd..............
.........dddcccccccddd..............
.........dddcccccccddd..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
